spring:
  application:
    name: robot
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtp

save_path: ${IMAGE_DIR}
excel_path: ${EXCEL_DIR}


server:
  port: 8081
